# local 환경
spring:
  config.activate.on-profile: local
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 8080

app:
  front-url: 'http://localhost:5173'

---
# test 환경
spring:
  config.activate.on-profile: test
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 8080