spring:
  config.activate.on-profile: local

verification-token:
  aes-secret: ${EMAIL_TOKEN_AES_SECRET}
  hmac-secret: ${EMAIL_TOKEN_HMAC_SECRET}
  expiration: ${EMAIL_TOKEN_EXPIRATION}

db:
  aes-secret: ${LOCAL_DB_AES_SECRET}

---
spring:
  config.activate.on-profile: test

verification-token:
  aes-secret: ${EMAIL_TOKEN_AES_SECRET}
  hmac-secret: ${EMAIL_TOKEN_HMAC_SECRET}
  expiration: ${EMAIL_TOKEN_EXPIRATION}

db:
  aes-secret: ${TEST_DB_AES_SECRET}