# local 환경
spring:
  config.activate.on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      username: default

---
# test 환경
spring:
  config.activate.on-profile: test
  data:
    redis:
      host:
      port:
      username: