spring:
  config.activate.on-profile: local
resilience4j:
  circuitbreaker:
    instances:
      dbWriter:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20            # 최근 20회 기준
        minimumNumberOfCalls: 10
        failureRateThreshold: 50         # 실패율 50% 이상이면 OPEN
        waitDurationInOpenState: 5s      # OPEN 유지 시간
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.dao.DeadlockLoserDataAccessException
          - org.springframework.dao.CannotAcquireLockException
          - org.springframework.dao.TransientDataAccessException
          - java.sql.SQLTransientException
          - java.sql.SQLRecoverableException
        ignoreExceptions:
          - java.lang.IllegalArgumentException # 재시도해도 소용없는 것들
  retry:
    instances:
      dbWriter:
        maxAttempts: 1                   # 동기 재시도 사실상 "없음"(=0회 추가)
        waitDuration: 0
        retryExceptions:
          - org.springframework.dao.TransientDataAccessException

---
spring:
  config.activate.on-profile: test
resilience4j:
  circuitbreaker:
    instances:
      dbWriter:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20            # 최근 20회 기준
        minimumNumberOfCalls: 10
        failureRateThreshold: 50         # 실패율 50% 이상이면 OPEN
        waitDurationInOpenState: 5s      # OPEN 유지 시간
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.dao.DeadlockLoserDataAccessException
          - org.springframework.dao.CannotAcquireLockException
          - org.springframework.dao.TransientDataAccessException
          - java.sql.SQLTransientException
          - java.sql.SQLRecoverableException
        ignoreExceptions:
          - java.lang.IllegalArgumentException # 재시도해도 소용없는 것들
  retry:
    instances:
      dbWriter:
        maxAttempts: 1
        waitDuration: 0
        retryExceptions:
          - org.springframework.dao.TransientDataAccessException