spring:
  config.activate.on-profile: local
resilience4j:
  circuitbreaker:
    instances:
      dbWriter:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20            # 최근 20회 기준
        minimumNumberOfCalls: 10
        failureRateThreshold: 50         # 실패율 50% 이상이면 OPEN
        waitDurationInOpenState: 10s      # OPEN 유지 시간
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - java.lang.IllegalArgumentException
      fcm:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        slowCallRateThreshold: 50 # slow call 50% 초과시 차단(open)
        slowCallDurationThreshold: 5s # api 응답이 느린 경우 10s
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        writableStackTraceEnabled: true # false
        ignoreExceptions:
          - com.rouby.notification.notificationEvent.infrastructure.exception.NotificationEventFcmException
      assistant:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 10s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - com.rouby.assistant.prompt.infrastructure.exception.AssistantInfraException
  retry:
    instances:
      assistant:
        maxAttempts: 3

---
spring:
  config.activate.on-profile: test
resilience4j:
  circuitbreaker:
    instances:
      dbWriter:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20            # 최근 20회 기준
        minimumNumberOfCalls: 10
        failureRateThreshold: 50         # 실패율 50% 이상이면 OPEN
        waitDurationInOpenState: 5s      # OPEN 유지 시간
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - java.lang.IllegalArgumentException
      fcm:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 10s
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        writableStackTraceEnabled: false
        ignoreExceptions:
          - com.rouby.notification.notificationEvent.infrastructure.exception.NotificationEventFcmException
      assistant:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 200ms
        permittedNumberOfCallsInHalfOpenState: 1
        ignoreExceptions:
          - com.rouby.assistant.prompt.infrastructure.exception.AssistantInfraException
  retry:
    instances:
      assistant:
        maxAttempts: 3