POST {{url}}/test/notification-events
Content-Type: application/json

{
  "userId": 0,
  "tokenProviderType": "FCM",
  "deviceToken": "",
  "title": "Rouby - 브리핑 알림",
  "body": "{}님, {}의 브리핑이 도착했습니다.",
  "url": "http://localhost:5173",
  "notificationType": "BRIEFING"
}