POST {{url}}/api/v1/schedules
content-type: application/json

{
  "title": "하이들 모임!",
  "memo": "뭉티기 먹을 것!",
  "alarmOffsetMinutes": 1440,
  "startAt": "2026-07-25T10:30",
  "endAt": "2026-07-25T22:30",
  "routineActivateDate": "2026-07-11",
  "recurrenceRule": {
    "freq": "MONTHLY",
    "interval": 1,
    "byDay": "MO",
    "until": "2100-12-30T00:00:00+09:00"
  }
}