### 이메일 인증 요청
POST {{url}}/api/v1/users/email-verification/request
Content-Type: application/json

{
  "email": "{{valid-email}}"
}

### 이메일 인증 코드 확인
POST {{url}}/api/v1/users/email-verification/verify
Content-Type: application/json

{
  "email": "{{valid-email}}",
  "code": "{{valid-email-verification-code}}"
}

> {%
  client.global.set("verificationToken", response.body.token);
%}


### 회원가입 API
POST {{url}}/api/v1/users
content-type: application/json
Authorization: EmailVerification {{verificationToken}}

{
  "email": "{{valid-email}}",
  "password": "{{valid-password}}"
}

### 회원가입 API (실패 - 비밀번호 검증 오류)
POST {{url}}/api/v1/users
content-type: application/json

{
  "email": "invalid@hidle.com",
  "password": "qwe3"
}

### 로그인
POST {{url}}/api/v1/auth/login
content-type: application/json

{
  "email": "{{valid-email}}",
  "password": "{{valid-password}}"
}

### 유저정보 업데이트
PATCH http://localhost:8080/api/v1/users/user-info
Content-Type: application/json
Authorization: {{access_token}}

{
  "nickname": "루비짱",
  "healthStatusKeywords": ["스트레스", "우울감"],
  "profileKeywords": ["운동", "명상"],
  "dailyStartTime": "07:00",
  "dailyEndTime": "23:00"
}
