POST {{url}}/api/v1/users/devices
content-type: application/json
uthorization: Bearer {{access_token}}

{
  "tokenProvider": "FCM",
  "deviceToken": "1234",
  "appType": "WEB",
  "appVersion": "string",
  "deviceType": "DESKTOP",
  "os": "string",
  "browser": "string",
  "userAgent": "string"
}