### 이메일 인증 요청
POST {{url}}/api/v1/users/email-verification/request
Content-Type: application/json

{
  "email": "{{valid-email}}"
}

### 이메일 인증 코드 확인
POST {{url}}/api/v1/users/email-verification/verify
Content-Type: application/json

{
  "email": "{{valid-email}}",
  "code": "{{valid-email-verification-code}}"
}

### 회원가입 API
POST {{url}}/api/v1/users
content-type: application/json

{
  "email": "{{valid-email}}",
  "password": "{{valid-password}}"
}

### 회원가입 API (실패 - 비밀번호 검증 오류)
POST {{url}}/api/v1/users
content-type: application/json

{
  "email": "invalid@hidle.com",
  "password": "qwe3"
}

### 로그인
POST {{url}}/api/v1/auth/login
content-type: application/json

{
  "email": "{{valid-email}}",
  "password": "{{valid-password}}"
}
