POST {{url}}/api/v1/users/devices
content-type: application/json
Authorization: Bearer {{access_token}}

{
  "tokenProvider": "FCM",
  "deviceToken": "1234",
  "appType": "WEB",
  "appVersion": "string",
  "deviceType": "DESKTOP",
  "os": "string",
  "browser": "string",
  "userAgent": "string"
}


###
DELETE {{url}}/api/v1/users/devices?tokenProvider=FCM&deviceToken=1234
Authorization: Bearer {{access_token}}


###
DELETE {{url}}/api/v1/users/devices/all
Authorization: Bearer {{access_token}}
