services:
  pgsql:
    container_name: rouby-db
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rouby
      TZ: Asia/Seoul
    volumes:
      - postgres-data:/var/lib/postgresql/data
#      - ./infra/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

  redis:
    container_name: rouby-redis
    image: redis:8
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data: